import type { DailyWord } from "./words";

type Seed = [string, string, string, string, string, string];

const monthSlug: Record<number, string> = { 9: "september", 10: "october", 11: "november", 12: "december" };

function makeMonth(month: number, seeds: Seed[]): DailyWord[] {
  return seeds.map(([word, meaning, origin, example, translation, imageAlt], index) => ({
    month,
    day: index + 1,
    word,
    pronunciation: "눌러서 발음 듣기",
    meaning,
    description: `${meaning}의 뜻으로 일상에서 자주 만나는 단어`,
    originTitle: `${word}의 오래된 뿌리를 따라가 봐요`,
    origin,
    example,
    translation,
    image: `/assets/${monthSlug[month]}/${String(index + 1).padStart(2, "0")}.jpg`,
    imageAlt,
  }));
}

export const SEPTEMBER_WORDS = makeMonth(9, [
  ["learn", "배우다", "고대 영어 leornian은 지식이나 기술을 얻고 길러 간다는 뜻이었어요.", "We learn something new every day.", "우리는 날마다 새로운 것을 배워.", "빛나는 책을 펼친 토끼"],
  ["study", "공부하다", "라틴어 studium은 열정과 부지런한 관심을 뜻했고, 프랑스어를 거쳐 study가 됐어요.", "I study English after dinner.", "나는 저녁 식사 뒤에 영어를 공부해.", "지도와 책을 공부하는 여우"],
  ["school", "학교", "그리스어 skhole는 뜻밖에도 여가를 뜻했어요. 여가에 토론하고 배우던 곳이 학교가 됐죠.", "Our school has a small garden.", "우리 학교에는 작은 정원이 있어.", "숲속의 작은 학교"],
  ["lesson", "수업, 교훈", "라틴어 lectio는 읽기나 읽어 주는 것을 뜻했어요. 같은 뿌리가 lecture에도 남아 있어요.", "Today’s lesson is about stars.", "오늘 수업은 별에 관한 거야.", "별을 가르치는 부엉이"],
  ["memory", "기억", "라틴어 memoria는 기억과 회상을 뜻해요. remember, memorial도 같은 말 가족이에요.", "This song brings back a happy memory.", "이 노래는 행복한 기억을 떠올리게 해.", "빛나는 추억을 든 생쥐"],
  ["focus", "집중하다", "라틴어 focus는 원래 집의 불자리, 난로였어요. 빛과 열이 모이는 중심이 지금의 집중이 됐죠.", "Focus on one task at a time.", "한 번에 한 가지 일에 집중해.", "돋보기로 살피는 고양이"],
  ["practice", "연습", "그리스어 praktikos는 행동에 알맞은이라는 뜻이에요. 머리로만 알지 않고 실제로 해 보는 일이죠.", "Daily practice builds confidence.", "매일의 연습은 자신감을 키워.", "바이올린을 연습하는 곰"],
  ["skill", "기술, 솜씨", "고대 노르스어 skil은 구별과 이해를 뜻했어요. 잘 판단해 해내는 능력으로 뜻이 넓어졌죠.", "Cooking is a useful skill.", "요리는 유용한 기술이야.", "작은 배를 만드는 다람쥐"],
  ["talent", "재능", "talent는 고대의 무게와 화폐 단위였어요. 성경의 비유를 거치며 타고난 능력이라는 뜻이 생겼죠.", "She has a talent for music.", "그녀는 음악에 재능이 있어.", "무대에서 노래하는 새"],
  ["effort", "노력", "옛 프랑스어 esforcier는 힘을 내다라는 뜻이에요. 힘을 밖으로 끌어내는 이미지가 담겼어요.", "Your effort will make a difference.", "네 노력은 변화를 만들 거야.", "수레를 언덕 위로 미는 토끼"],
  ["progress", "진전, 발전", "라틴어 progredi는 앞으로 걸어가다라는 뜻이에요. pro는 앞으로, gradi는 걷다예요.", "We made steady progress this week.", "우리는 이번 주에 꾸준히 발전했어.", "이정표를 지나는 달팽이"],
  ["improve", "향상시키다", "옛 프랑스어 표현 en prou는 이익이 되도록이라는 뜻이었고 영어에서 더 낫게 만들다로 자리 잡았어요.", "Reading can improve your vocabulary.", "독서는 어휘력을 향상시킬 수 있어.", "연을 고쳐 더 멋지게 만드는 여우"],
  ["discover", "발견하다", "라틴어 dis는 벗겨 냄, cooperire는 덮음을 뜻해요. 덮개를 열어 보이는 것이 발견이 됐죠.", "We discovered a hidden path.", "우리는 숨겨진 길을 발견했어.", "수정 동굴을 발견한 친구들"],
  ["explore", "탐험하다", "라틴어 explorare는 살피고 조사하다라는 뜻이에요. 낯선 곳을 자세히 알아보는 행동이죠.", "Let’s explore the forest together.", "우리 함께 숲을 탐험하자.", "나침반을 든 숲속 탐험대"],
  ["question", "질문", "라틴어 quaerere는 찾고 묻다라는 뜻이에요. quest도 답을 찾아 나서는 같은 뿌리의 단어예요.", "Ask a question when you are curious.", "궁금할 때는 질문해.", "반딧불 물음표를 보는 토끼"],
  ["answer", "대답", "고대 영어 andswaru는 맞서 하는 말이라는 뜻이었어요. 질문에 마주 내놓는 말이 답이 된 거예요.", "Her answer was clear and kind.", "그녀의 대답은 분명하고 친절했어.", "빛나는 열쇠를 보여 주는 부엉이"],
  ["idea", "생각, 아이디어", "그리스어 idea는 보이는 모습이나 형태를 뜻했어요. 마음속에 떠오른 모습이라는 뜻으로 발전했죠.", "I have an idea for our project.", "우리 프로젝트에 대한 아이디어가 있어.", "전구 모양 꽃을 발견한 아이"],
  ["create", "창조하다", "라틴어 creare는 만들고 자라게 하다라는 뜻이에요. creator, creature도 같은 뿌리예요.", "Create a story with three pictures.", "그림 세 장으로 이야기를 만들어 봐.", "종이 세상을 그리는 토끼"],
  ["imagine", "상상하다", "라틴어 imago는 모습과 형상을 뜻해요. 눈앞에 없는 모습을 마음에 그리는 일이 imagine이 됐죠.", "Imagine a city in the clouds.", "구름 속 도시를 상상해 봐.", "구름 고래를 타는 여우"],
  ["design", "설계하다, 디자인", "라틴어 designare는 표시하고 계획하다라는 뜻이에요. 머릿속 계획에 선을 그어 보이는 일이죠.", "They designed a cozy tree house.", "그들은 아늑한 나무집을 설계했어.", "나무집을 설계하는 비버"],
  ["pattern", "무늬, 규칙", "중세 영어 patron은 본보기나 모형을 뜻했고 발음과 철자가 변해 pattern이 됐어요.", "I found a pattern in the numbers.", "나는 숫자에서 규칙을 찾았어.", "색 타일을 배열하는 새들"],
  ["method", "방법", "그리스어 methodos는 따라가는 길이라는 뜻이에요. meta와 hodos, 곧 길을 좇는다는 이미지예요.", "This method saves a lot of time.", "이 방법은 시간을 많이 아껴 줘.", "요리법을 따라가는 부엉이"],
  ["habit", "습관", "라틴어 habitus는 몸가짐이나 상태를 뜻했어요. 되풀이해 몸에 밴 행동을 가리키게 됐죠.", "Walking is a healthy habit.", "걷기는 건강한 습관이야.", "매일 화분에 물을 주는 생쥐"],
  ["routine", "일과, 반복 습관", "프랑스어 route에서 나온 말로, 늘 다니는 작은 길처럼 되풀이하는 순서를 뜻하게 됐어요.", "My morning routine starts at seven.", "나의 아침 일과는 일곱 시에 시작해.", "아침 준비를 하는 곰"],
  ["patience", "인내", "라틴어 pati는 견디다라는 뜻이에요. 서두르지 않고 어려움을 견디는 마음이 patience예요.", "Gardening teaches us patience.", "정원 가꾸기는 우리에게 인내를 가르쳐.", "싹을 기다리는 토끼"],
  ["challenge", "도전", "라틴어 calumnia에서 프랑스어를 거치며 맞서 요구하거나 시험한다는 뜻으로 발전했어요.", "The puzzle was a fun challenge.", "그 퍼즐은 재미있는 도전이었어.", "징검돌에 도전하는 친구들"],
  ["achieve", "이루다", "옛 프랑스어 achever는 끝이나 머리에 이르다라는 뜻이에요. 목표의 끝까지 닿는 모습이죠.", "You can achieve your goal.", "너는 목표를 이룰 수 있어.", "정상 깃발에 닿은 작은 등반가"],
  ["success", "성공", "라틴어 succedere는 뒤따라오다, 잘되어 가다라는 뜻이었어요. 어떤 결과가 이어져 오는 것이 성공이 됐죠.", "Teamwork made the event a success.", "협동이 그 행사를 성공으로 만들었어.", "완성한 다리를 축하하는 팀"],
  ["wisdom", "지혜", "고대 영어 wis는 알고 현명하다는 뜻이에요. 지식을 삶에 잘 쓰는 힘을 가리켜요.", "Her wisdom helped us choose well.", "그녀의 지혜는 우리가 잘 선택하도록 도왔어.", "빛나는 두루마리를 나누는 늙은 부엉이"],
  ["knowledge", "지식", "고대 영어 cnawan, 곧 알다에서 나온 knowledge는 알고 있는 것들의 모음을 뜻해요.", "Knowledge grows when we share it.", "지식은 나눌 때 자라.", "책으로 가득한 도서관 나무"],
]);

export const OCTOBER_WORDS = makeMonth(10, [
  ["mystery", "수수께끼, 미스터리", "그리스어 mysterion은 비밀 의식이나 감춰진 일을 뜻했어요.", "The old key opened a mystery.", "그 오래된 열쇠가 수수께끼의 문을 열었어.", "비밀 문을 찾은 토끼 탐정"],
  ["magic", "마법", "그리스어 magikos는 고대 페르시아의 사제 계층 Magi와 관련된 말이에요.", "The garden looked full of magic.", "그 정원은 마법으로 가득해 보였어.", "황금 불꽃을 만드는 여우 마술사"],
  ["phantom", "유령, 환영", "그리스어 phantasma는 나타나는 모습이나 환영을 뜻했어요.", "A friendly phantom waved upstairs.", "친절한 유령이 위층에서 손을 흔들었어.", "다락방의 다정한 투명 유령"],
  ["monster", "괴물", "라틴어 monstrum은 경고의 징조를 뜻하고 monere, 곧 경고하다와 이어져요.", "The little monster loved warm tea.", "그 작은 괴물은 따뜻한 차를 좋아했어.", "차를 나누는 복슬복슬 괴물"],
  ["vampire", "흡혈귀", "vampire는 세르비아어 계통의 vampir가 여러 유럽 언어를 거쳐 영어에 들어왔어요.", "The tiny vampire preferred tomato juice.", "그 작은 흡혈귀는 토마토주스를 더 좋아했어.", "망토를 입은 예의 바른 작은 박쥐"],
  ["nightmare", "악몽", "고대 영어 mare는 잠든 사람을 짓누른다고 믿은 밤의 괴물을 뜻했어요.", "The nightmare faded in the morning.", "악몽은 아침이 되자 사라졌어.", "어두운 구름을 별로 바꾸는 아이"],
  ["shadow", "그림자", "고대 영어 sceadu는 그늘과 어둠을 뜻했어요. 빛을 가린 자리에 생기는 모양이죠.", "Our shadows danced on the wall.", "우리 그림자가 벽에서 춤췄어.", "등불로 동물 그림자를 만드는 친구들"],
  ["candle", "초", "라틴어 candere는 밝게 빛나다라는 뜻이에요. candid도 같은 밝음의 뿌리를 가졌어요.", "She lit a candle by the window.", "그녀는 창가에 초를 켰어.", "빛나는 초를 든 생쥐"],
  ["lantern", "등불", "그리스어 lampter는 비추는 횃불을 뜻했고 라틴어와 프랑스어를 거쳐 lantern이 됐어요.", "Lanterns guided us through the woods.", "등불이 숲길을 안내했어.", "종이등이 이어진 숲길"],
  ["costume", "의상, 분장", "이탈리아어 costume는 관습과 옷차림을 뜻했어요. 특정 역할에 맞춘 옷이란 뜻이 커졌죠.", "He wore a dragon costume.", "그는 용 의상을 입었어.", "여러 의상을 입어 보는 동물 친구들"],
  ["mask", "가면", "중세 라틴어 masca는 유령이나 가면을 뜻했어요. 얼굴을 감춰 다른 모습이 되게 하죠.", "The fox painted a silver mask.", "여우는 은빛 가면을 칠했어.", "축제 가면을 칠하는 여우"],
  ["festival", "축제", "라틴어 festivus는 즐겁고 축제다운이라는 뜻이에요. feast도 가까운 말 가족이에요.", "The village festival began at sunset.", "마을 축제는 해 질 무렵 시작됐어.", "달빛 아래 마을 행진"],
  ["pumpkin", "호박", "pumpkin은 그리스어 pepon, 곧 잘 익은 큰 멜론을 뜻하던 말에서 여러 언어를 거쳐 왔어요.", "We made soup with a pumpkin.", "우리는 호박으로 수프를 만들었어.", "웃는 호박을 꾸미는 토끼들"],
  ["autumn", "가을", "라틴어 autumnus가 프랑스어를 거쳐 영어 autumn이 됐어요. 영국 영어에서 널리 쓰여요.", "Autumn painted the leaves gold.", "가을이 나뭇잎을 금빛으로 물들였어.", "낙엽 속에서 노는 친구들"],
  ["harvest", "수확", "고대 영어 hærfest는 원래 가을 자체를 뜻했어요. 곡식을 거두는 계절이 수확이라는 뜻이 됐죠.", "The farmers celebrated the harvest.", "농부들은 수확을 축하했어.", "알록달록한 작물 바구니"],
  ["orchard", "과수원", "고대 영어 ortgeard는 식물 정원이라는 뜻이에요. geard는 울타리 친 뜰을 가리켰어요.", "We picked apples in the orchard.", "우리는 과수원에서 사과를 땄어.", "사과를 따는 숲속 친구들"],
  ["spell", "주문, 철자를 쓰다", "고대 영어 spell은 이야기나 말을 뜻했어요. 특별한 말은 주문이 되고, 글자를 말하는 일은 철자법이 됐죠.", "The wizard whispered a gentle spell.", "마법사는 다정한 주문을 속삭였어.", "반짝이는 말을 속삭이는 마법사"],
  ["charm", "매력, 부적", "라틴어 carmen은 노래나 주문을 뜻했어요. 사람을 홀리는 말과 매력이라는 뜻으로 넓어졌죠.", "Her warm smile had a special charm.", "그녀의 따뜻한 미소에는 특별한 매력이 있었어.", "노래하는 작은 별 부적"],
  ["potion", "마법의 물약", "라틴어 potio는 마시는 것이라는 뜻이에요. drink와 같은 평범한 뜻에서 신비한 물약으로 발전했죠.", "The blue potion smelled like mint.", "파란 물약에서는 민트 향이 났어.", "민트빛 물약을 만드는 동물들"],
  ["crystal", "수정", "그리스어 krystallos는 얼음과 투명한 수정을 뜻했어요. 옛사람은 수정을 영원히 녹지 않는 얼음이라 생각했죠.", "A crystal sparkled in the cave.", "동굴 속 수정이 반짝였어.", "얼음처럼 빛나는 동굴 수정"],
  ["secret", "비밀", "라틴어 secretus는 따로 떼어 놓은, 숨겨 둔이라는 뜻이에요.", "Can you keep this secret?​", "이 비밀을 지켜 줄 수 있니?", "작은 상자에 비밀을 넣는 친구들"],
  ["puzzle", "퍼즐, 수수께끼", "puzzle은 오래된 영어 pose, 곧 당황하게 하다와 관련 있다고 보지만 정확한 초기 역사는 불분명해요.", "We finished the puzzle together.", "우리는 함께 퍼즐을 완성했어.", "별 모양 퍼즐을 맞추는 친구들"],
  ["maze", "미로", "maze는 중세 영어에서 혼란스럽게 하다라는 뜻으로 쓰였어요. amaze에도 놀라 어리둥절한 느낌이 남아 있죠.", "A red thread led through the maze.", "빨간 실이 미로를 통과하도록 이끌었어.", "붉은 실이 이어진 정원 미로"],
  ["riddle", "수수께끼", "고대 영어 rædels는 해석하거나 추측해야 할 것을 뜻했어요. read와도 오래된 뿌리가 이어져요.", "The owl gave us a clever riddle.", "부엉이가 재치 있는 수수께끼를 냈어.", "두루마리 수수께끼를 낸 부엉이"],
  ["legend", "전설", "라틴어 legenda는 읽어야 할 이야기라는 뜻이에요. 성인의 삶을 낭독하던 이야기에서 넓어졌죠.", "The mountain has an old legend.", "그 산에는 오래된 전설이 있어.", "산 위 용의 전설을 듣는 아이들"],
  ["myth", "신화", "그리스어 mythos는 말, 이야기, 전승을 뜻했어요.", "The book retells a Greek myth.", "그 책은 그리스 신화를 새롭게 들려줘.", "별자리 신화를 읽는 친구들"],
  ["story", "이야기", "story와 history는 모두 그리스어 historia, 곧 알아봄과 기록에서 이어진 말이에요.", "Grandma told us a funny story.", "할머니가 재미있는 이야기를 들려주셨어.", "모닥불 곁에서 이야기 듣는 동물들"],
  ["fantasy", "환상, 판타지", "그리스어 phantasia는 상상 속에 모습을 나타내는 힘을 뜻했어요.", "The novel is full of fantasy.", "그 소설은 환상으로 가득해.", "공중 성을 여행하는 친구들"],
  ["wonder", "경이로움", "고대 영어 wundor는 놀랍고 신기한 것을 뜻했어요. 놀라움과 궁금함을 함께 담은 말이에요.", "We looked at the moon in wonder.", "우리는 경이로운 마음으로 달을 바라봤어.", "커다란 달을 올려다보는 친구들"],
  ["strange", "이상한, 낯선", "라틴어 extraneus는 바깥에서 온이라는 뜻이에요. 낯선 곳에서 온 것이 strange가 됐죠.", "A strange little door appeared.", "이상한 작은 문이 나타났어.", "나무에 생긴 낯선 작은 문"],
  ["eerie", "으스스한", "eerie는 스코틀랜드 영어에서 두렵고 기묘한 느낌을 나타내던 말이에요.", "An eerie song drifted from the tower.", "탑에서 으스스한 노래가 흘러나왔어.", "달빛 탑에서 흘러나오는 음표"],
]);

export const NOVEMBER_WORDS = makeMonth(11, [
  ["community", "공동체", "라틴어 communis는 함께 나누는이라는 뜻이에요. common과 같은 뿌리예요.", "Our community planted a garden.", "우리 공동체는 정원을 만들었어.", "함께 정원을 만드는 이웃들"],
  ["neighbor", "이웃", "고대 영어 neahgebur는 가까이에 사는 사람이라는 뜻이에요. nigh와 dweller의 이미지가 합쳐졌죠.", "A neighbor brought us warm bread.", "이웃이 따뜻한 빵을 가져다주었어.", "빵을 건네는 이웃 동물"],
  ["family", "가족", "라틴어 familia는 한 집에 속한 사람들을 뜻했어요. 시간이 지나 혈연과 돌봄의 집단을 가리키게 됐죠.", "My family eats dinner together.", "우리 가족은 함께 저녁을 먹어.", "한 식탁에 모인 가족"],
  ["friend", "친구", "고대 영어 freond는 사랑하다라는 동사와 이어져요. 아끼고 사랑하는 사람이 친구였죠.", "A good friend listens carefully.", "좋은 친구는 귀 기울여 들어 줘.", "벤치에서 이야기하는 두 친구"],
  ["citizen", "시민", "라틴어 civis는 도시국가의 구성원을 뜻했어요. city와 같은 뿌리의 말이에요.", "Every citizen can help the town.", "모든 시민이 마을을 도울 수 있어.", "마을 지도를 함께 보는 시민들"],
  ["society", "사회", "라틴어 socius는 동료나 친구를 뜻해요. 사람들이 관계를 맺은 큰 모임이 society가 됐죠.", "Society changes through cooperation.", "사회는 협력으로 변화해.", "커다란 원에 모인 여러 동물"],
  ["culture", "문화", "라틴어 cultura는 땅을 가꾸는 일을 뜻했어요. 마음과 삶을 가꾼다는 뜻으로 넓어졌죠.", "Food is an important part of culture.", "음식은 문화의 중요한 부분이야.", "여러 음식을 나누는 축제"],
  ["custom", "관습", "라틴어 consuetudo는 익숙해진 습관을 뜻했어요. 공동체가 오래 되풀이한 방식이에요.", "It is our custom to greet guests.", "손님을 맞이하는 것은 우리의 관습이야.", "손님을 맞이하는 마을"],
  ["tradition", "전통", "라틴어 tradere는 건네주다라는 뜻이에요. 세대에서 세대로 전해 주는 것이 tradition이죠.", "This dance is a family tradition.", "이 춤은 우리 가족의 전통이야.", "춤을 다음 세대에 가르치는 가족"],
  ["language", "언어", "라틴어 lingua는 혀와 말을 뜻해요. 프랑스어를 거쳐 language가 됐죠.", "Language helps us share ideas.", "언어는 생각을 나누게 도와줘.", "말풍선 새를 날리는 친구들"],
  ["dialogue", "대화", "그리스어 dialogos는 말을 주고받는 것을 뜻해요. dia는 사이를 가로질러라는 의미예요.", "The story begins with a short dialogue.", "이야기는 짧은 대화로 시작해.", "다리 양쪽에서 대화하는 친구들"],
  ["promise", "약속", "라틴어 promittere는 앞으로 내보내다라는 뜻이에요. 미래를 향해 말을 내놓는 것이 약속이죠.", "I promise to return the book.", "그 책을 돌려주겠다고 약속할게.", "새끼손가락을 거는 친구들"],
  ["trust", "신뢰", "고대 노르스어 traust는 도움과 든든함을 뜻했어요. 기대어도 안전한 마음이 trust예요.", "Trust grows through honest actions.", "신뢰는 정직한 행동으로 자라.", "밧줄 다리에서 서로 돕는 친구들"],
  ["respect", "존중", "라틴어 respicere는 다시 바라보다라는 뜻이에요. 상대를 주의 깊게 바라보는 태도가 존중이 됐죠.", "We respect different opinions.", "우리는 서로 다른 의견을 존중해.", "서로의 그림을 감상하는 친구들"],
  ["justice", "정의", "라틴어 justus는 올바르고 공정한이라는 뜻이에요.", "The judge worked for justice.", "판사는 정의를 위해 일했어.", "균형 잡힌 저울을 든 부엉이"],
  ["peace", "평화", "라틴어 pax는 평화와 합의를 뜻했어요. pact도 서로 맺은 약속이라는 같은 뿌리예요.", "They planted an olive tree for peace.", "그들은 평화를 위해 올리브나무를 심었어.", "올리브나무를 심는 친구들"],
  ["vote", "투표하다", "라틴어 votum은 소원이나 엄숙한 약속을 뜻했어요. 선택을 공식적으로 밝히는 표가 됐죠.", "We vote for our class captain.", "우리는 반장을 뽑기 위해 투표해.", "상자에 표를 넣는 동물들"],
  ["leader", "지도자", "고대 영어 lædan은 길을 안내하다라는 뜻이에요. 앞에서 길을 보여 주는 사람이 leader예요.", "A leader helps the team move forward.", "지도자는 팀이 앞으로 나아가게 도와.", "등불로 길을 안내하는 여우"],
  ["team", "팀", "고대 영어 team은 끌어당기는 동물의 무리를 뜻했어요. 함께 힘을 모으는 집단이란 뜻으로 넓어졌죠.", "Our team solved the problem.", "우리 팀은 문제를 해결했어.", "수레를 함께 끄는 동물 팀"],
  ["cooperate", "협력하다", "라틴어 co는 함께, operari는 일하다는 뜻이에요. 말 그대로 함께 일하는 것이죠.", "We cooperate to clean the park.", "우리는 공원을 청소하려고 협력해.", "공원을 함께 청소하는 친구들"],
  ["share", "나누다", "고대 영어 scearu는 잘라 나눈 몫을 뜻했어요. 자신의 몫을 다른 이와 나누는 행동이죠.", "Let’s share the last apple.", "마지막 사과를 나눠 먹자.", "사과 하나를 나누는 친구들"],
  ["support", "지지하다, 돕다", "라틴어 supportare는 아래에서 받쳐 나르다라는 뜻이에요.", "Her friends support her dream.", "친구들은 그녀의 꿈을 응원해.", "무대를 아래에서 받쳐 주는 친구들"],
  ["volunteer", "자원봉사자", "라틴어 voluntas는 의지와 자발적인 마음을 뜻해요. 스스로 나선 사람이 volunteer예요.", "I volunteer at the animal shelter.", "나는 동물 보호소에서 자원봉사해.", "동물 집을 고쳐 주는 자원봉사자"],
  ["charity", "자선, 나눔", "라틴어 caritas는 소중히 여기는 사랑을 뜻했어요. 도움이 필요한 이를 돌보는 마음으로 이어졌죠.", "The concert raised money for charity.", "그 공연은 자선을 위한 기금을 모았어.", "나눔 상자에 물건을 넣는 마을"],
  ["kindness", "친절", "고대 영어 gecynde는 자연스럽고 다정하다는 뜻으로 쓰였어요.", "A small kindness changed his day.", "작은 친절이 그의 하루를 바꿨어.", "비를 맞는 새에게 우산을 씌워 주는 토끼"],
  ["generous", "관대한, 너그러운", "라틴어 generosus는 좋은 가문에서 난 고귀한이라는 뜻이었고, 고귀한 마음씨라는 뜻으로 넓어졌어요.", "She was generous with her time.", "그녀는 기꺼이 시간을 내어 주었어.", "많은 빵을 나누는 곰"],
  ["empathy", "공감", "그리스어 em은 안에, pathos는 느낌을 뜻해요. 다른 사람의 느낌 안으로 들어가 이해하는 마음이죠.", "Empathy helps us understand others.", "공감은 다른 사람을 이해하게 도와줘.", "서로의 감정 빛을 바라보는 친구들"],
  ["harmony", "조화", "그리스어 harmonia는 여러 부분을 꼭 맞게 잇는다는 뜻이에요. 음악과 관계의 어울림을 가리켜요.", "Their voices blended in harmony.", "그들의 목소리는 조화롭게 어우러졌어.", "함께 합창하는 동물들"],
  ["unity", "단결, 하나 됨", "라틴어 unus는 하나라는 뜻이에요. 서로 다른 이들이 하나의 힘을 만드는 모습이 unity예요.", "The team showed unity in hard times.", "그 팀은 어려울 때 단결을 보여 줬어.", "하나의 큰 별을 함께 드는 친구들"],
  ["together", "함께", "고대 영어 togædere는 한 장소나 무리에 모인다는 뜻이에요.", "We can build it together.", "우리는 그것을 함께 만들 수 있어.", "큰 집을 함께 완성하는 마을"],
]);

export const DECEMBER_WORDS = makeMonth(12, [
  ["winter", "겨울", "고대 영어 winter는 영어의 아주 오래된 계절 이름이에요. 정확한 더 먼 뿌리는 확실하지 않아요.", "Winter arrived with a cold wind.", "차가운 바람과 함께 겨울이 왔어.", "눈 내리는 숲 마을"],
  ["snow", "눈", "고대 영어 snaw와 게르만계 단어에서 이어졌어요. snow는 명사와 동사로 모두 쓰여요.", "Soft snow covered the roof.", "부드러운 눈이 지붕을 덮었어.", "눈 덮인 지붕 위 토끼"],
  ["frost", "서리", "고대 영어 frost는 얼다라는 뜻의 오래된 게르만계 뿌리와 이어져요.", "Frost drew flowers on the window.", "서리가 창문에 꽃무늬를 그렸어.", "창문에 핀 서리꽃"],
  ["holiday", "휴일", "고대 영어 halig dæg는 거룩한 날이라는 뜻이었어요. 쉬고 기념하는 날 전체로 뜻이 넓어졌죠.", "The library closes for the holiday.", "도서관은 휴일에 문을 닫아.", "종이 달력의 빛나는 휴일"],
  ["celebrate", "축하하다", "라틴어 celebrare는 많은 사람이 모여 기리다라는 뜻이에요.", "We celebrate every small victory.", "우리는 작은 승리도 모두 축하해.", "작은 승리를 축하하는 친구들"],
  ["gift", "선물", "고대 노르스어 gift는 주는 것이라는 뜻이에요. give와 가까운 말 가족이에요.", "The handmade card was a lovely gift.", "손수 만든 카드는 사랑스러운 선물이었어.", "손수 만든 카드를 건네는 토끼"],
  ["present", "선물, 현재", "라틴어 praesens는 바로 앞에 있는이라는 뜻이에요. 눈앞에 내미는 것이 선물 present의 뜻으로도 이어졌죠.", "This book is a present for you.", "이 책은 너를 위한 선물이야.", "책 선물을 내미는 여우"],
  ["surprise", "놀라움", "프랑스어 surprendre는 갑자기 붙잡다라는 뜻이에요. 예상하지 못한 일이 우리를 덥석 잡는 느낌이죠.", "The party was a wonderful surprise.", "그 파티는 멋진 깜짝 선물이었어.", "상자에서 별이 솟는 깜짝 파티"],
  ["merry", "즐거운", "고대 영어 myrige는 즐겁고 기분 좋다는 뜻이에요.", "They wished us a merry evening.", "그들은 우리에게 즐거운 저녁을 기원했어.", "즐겁게 춤추는 숲속 친구들"],
  ["joy", "기쁨", "라틴어 gaudium이 프랑스어 joie를 거쳐 영어 joy가 됐어요.", "Her face shone with joy.", "그녀의 얼굴은 기쁨으로 빛났어.", "빛나는 얼굴로 웃는 아이"],
  ["hope", "희망", "고대 영어 hopa는 바라고 기대하는 마음을 뜻했어요.", "Hope kept the little lamp glowing.", "희망이 작은 등불을 계속 빛나게 했어.", "어둠 속 작은 희망의 등불"],
  ["wish", "소원", "고대 영어 wyscan은 바라거나 원하다는 뜻이에요.", "Make a wish before the candle goes out.", "초가 꺼지기 전에 소원을 빌어.", "촛불 앞에서 소원을 비는 친구들"],
  ["dream", "꿈", "고대 영어 dream은 기쁨이나 음악을 뜻하기도 했고, 중세 영어에서 잠의 꿈이라는 뜻이 자리 잡았어요.", "She dreams of flying above the sea.", "그녀는 바다 위를 나는 꿈을 꿔.", "별배를 타고 나는 토끼"],
  ["comfort", "위로, 편안함", "라틴어 confortare는 함께 힘을 북돋우다라는 뜻이에요. con은 함께, fortis는 강함이에요.", "Warm soup brought us comfort.", "따뜻한 수프가 우리에게 위로를 주었어.", "수프를 나누며 위로하는 친구들"],
  ["warmth", "따뜻함", "고대 영어 wearm에서 이어진 말로, 온기뿐 아니라 다정한 태도도 뜻해요.", "The fire filled the room with warmth.", "불이 방을 따뜻함으로 채웠어.", "난롯가에 모인 동물 가족"],
  ["home", "집, 고향", "고대 영어 ham은 머무는 집과 마을을 뜻했어요. 단순한 건물보다 돌아갈 곳의 느낌을 담아요.", "Home is where we feel safe.", "집은 우리가 안전하다고 느끼는 곳이야.", "눈길 끝의 따뜻한 집"],
  ["fireplace", "벽난로", "fire와 place가 합쳐진 말로, 집 안에서 불을 피우는 자리를 그대로 나타내요.", "We read beside the fireplace.", "우리는 벽난로 곁에서 책을 읽었어.", "벽난로 옆에서 책 읽는 친구들"],
  ["sparkle", "반짝이다", "중세 영어 spark는 불꽃의 작은 조각을 뜻해요. 작은 빛이 연이어 번쩍이는 모습이 sparkle이죠.", "Stars sparkle above the snowy hill.", "별들이 눈 덮인 언덕 위에서 반짝여.", "눈 언덕 위 반짝이는 별"],
  ["star", "별", "고대 영어 steorra에서 이어졌고 여러 인도유럽어에 닮은 오래된 별 이름이 남아 있어요.", "One bright star guided the travelers.", "밝은 별 하나가 여행자들을 안내했어.", "여행자를 인도하는 큰 별"],
  ["angel", "천사", "그리스어 angelos는 소식을 전하는 사자를 뜻해요.", "The child made a paper angel.", "아이는 종이 천사를 만들었어.", "종이 천사를 만드는 아이"],
  ["music", "음악", "그리스어 mousike는 무즈 여신들의 예술이라는 뜻이에요.", "Music drifted through the snowy street.", "음악이 눈 내리는 거리에 흘렀어.", "눈길에 흐르는 따뜻한 음악"],
  ["carol", "캐럴, 축가", "옛 프랑스어 carole은 사람들이 원을 그리며 부르는 춤노래를 뜻했어요.", "We sang a carol by the tree.", "우리는 나무 곁에서 캐럴을 불렀어.", "나무 둘레에서 노래하는 친구들"],
  ["souvenir", "기념품", "프랑스어 souvenir는 기억하다라는 뜻이에요. 여행을 기억하게 하는 물건이 기념품이 됐죠.", "I kept the ticket as a souvenir.", "나는 그 표를 기념품으로 간직했어.", "여행 표를 추억 상자에 넣는 토끼"],
  ["reflect", "돌아보다, 비추다", "라틴어 reflectere는 뒤로 굽히다라는 뜻이에요. 빛이 되돌아오듯 생각을 되돌아보는 뜻도 생겼죠.", "Take a moment to reflect on the year.", "잠시 한 해를 돌아봐.", "얼음 거울에 한 해를 비춰 보는 여우"],
  ["forgive", "용서하다", "고대 영어 forgiefan은 완전히 주다, 놓아주다라는 뜻이었어요.", "It can be brave to forgive.", "용서하는 일에는 용기가 필요할 수 있어.", "매듭을 풀고 화해하는 친구들"],
  ["reunion", "재회", "re는 다시, union은 하나 됨을 뜻해요. 헤어졌던 사람들이 다시 모이는 일이죠.", "Our reunion filled the house with laughter.", "우리의 재회는 집을 웃음으로 채웠어.", "기차역에서 다시 만난 친구들"],
  ["farewell", "작별", "중세 영어 fare well은 잘 지내며 가라는 인사였어요.", "They waved farewell at the station.", "그들은 역에서 작별 인사를 하며 손을 흔들었어.", "기차에 손 흔드는 친구들"],
  ["future", "미래", "라틴어 futurus는 앞으로 있게 될이라는 뜻이에요.", "The future begins with today’s choice.", "미래는 오늘의 선택에서 시작돼.", "새벽길을 향해 걷는 아이"],
  ["new", "새로운", "고대 영어 niwe에서 이어진 아주 오래된 단어예요. 여러 언어에 닮은 뿌리가 있어요.", "A new notebook waits on the desk.", "새 공책이 책상 위에서 기다리고 있어.", "새 공책의 첫 장을 여는 토끼"],
  ["resolution", "결심", "라틴어 resolvere는 다시 풀어내다라는 뜻이에요. 문제를 풀고 마음을 굳게 정한다는 뜻이 생겼죠.", "My resolution is to read every day.", "나의 결심은 매일 책을 읽는 거야.", "달력에 결심을 적는 친구들"],
  ["cheer", "응원, 환호", "옛 프랑스어 chiere는 얼굴 표정을 뜻했어요. 밝은 표정과 기운을 북돋는 말로 발전했죠.", "We cheer for one another.", "우리는 서로를 응원해.", "서로에게 깃발을 흔드는 친구들"],
]);
