import type { DailyWord } from "./words";

type Upgrade = [string, string, string, string, string];

const UPGRADES: Record<string, Upgrade> = {
  learn: ["acquire", "습득하다, 얻다", "라틴어 acquirere는 '더하여 얻다'라는 뜻이에요. 지식이나 기술을 차곡차곡 자기 것으로 만드는 모습을 담고 있어요.", "She acquired confidence through daily practice.", "그녀는 매일 연습하며 자신감을 얻었어."],
  study: ["delve", "깊이 파고들다", "고대 영어 delfan은 땅을 파다라는 뜻이에요. 주제를 깊게 조사하는 모습으로 뜻이 넓어졌죠.", "We delved into the history of the word.", "우리는 그 단어의 역사를 깊이 파고들었어."],
  school: ["academy", "교육 기관, 학술원", "그리스 철학자 플라톤이 가르치던 정원 Akademeia의 이름이 배움의 장소를 뜻하게 됐어요.", "The academy encourages creative thinking.", "그 교육 기관은 창의적인 사고를 장려해."],
  lesson: ["instruction", "가르침, 지시", "라틴어 instruere는 안에 차곡차곡 쌓아 올리다라는 뜻이에요. 지식을 마음속에 세우는 이미지죠.", "The instruction made the task much clearer.", "그 설명 덕분에 과제가 훨씬 분명해졌어."],
  memory: ["recollection", "회상, 기억", "라틴어 recollectus는 다시 모으다라는 뜻이에요. 흩어진 기억을 마음속에 다시 모으는 거예요.", "The melody stirred a vivid recollection.", "그 선율은 생생한 기억을 불러일으켰어."],
  focus: ["concentrate", "집중하다", "라틴어 centrum은 중심을 뜻해요. 생각과 힘을 한 중심으로 모으는 것이 concentrate예요.", "Concentrate on the details before deciding.", "결정하기 전에 세부 사항에 집중해."],
  practice: ["rehearse", "연습하다, 예행연습하다", "옛 프랑스어 rehercier는 땅을 다시 고르게 다듬다라는 뜻이었어요. 되풀이해 익힌다는 뜻으로 발전했죠.", "The musicians rehearsed until sunset.", "연주자들은 해 질 때까지 연습했어."],
  skill: ["proficiency", "숙련도, 능숙함", "라틴어 proficere는 앞으로 나아가다라는 뜻이에요. 꾸준히 발전해 능숙해진 상태를 가리켜요.", "Her proficiency grew with every project.", "그녀의 숙련도는 프로젝트마다 높아졌어."],
  talent: ["aptitude", "소질, 적성", "라틴어 aptus는 알맞게 맞춰진이라는 뜻이에요. 어떤 일을 잘 배울 수 있는 타고난 성향을 말해요.", "He showed an aptitude for languages.", "그는 언어에 소질을 보였어."],
  effort: ["endeavor", "노력, 힘써 시도하다", "중세 영어 dever는 의무를 뜻했어요. 해야 할 일을 향해 힘을 기울이는 뜻으로 자리 잡았죠.", "The expedition was a remarkable endeavor.", "그 탐험은 놀라운 노력이었어."],
  progress: ["advancement", "발전, 진보", "라틴어 abante는 앞쪽이라는 뜻이에요. 앞으로 나아가는 변화가 advancement가 됐어요.", "Technology brought rapid advancement.", "기술은 빠른 발전을 가져왔어."],
  improve: ["refine", "다듬다, 개선하다", "re와 fine이 만나 불순물을 거듭 걸러 더 순수하게 만든다는 뜻에서 시작했어요.", "We refined the plan after the discussion.", "우리는 토론 뒤 계획을 더 다듬었어."],
  discover: ["uncover", "발견하다, 밝혀내다", "un과 cover가 합쳐져 덮개를 벗긴다는 뜻이에요. 감춰진 사실을 드러내는 데도 쓰여요.", "The researchers uncovered an important clue.", "연구자들은 중요한 단서를 밝혀냈어."],
  explore: ["investigate", "조사하다, 탐구하다", "라틴어 investigare는 발자국을 따라가다라는 뜻이에요. 흔적을 좇아 진실을 알아내는 모습이죠.", "The team investigated the unusual pattern.", "그 팀은 특이한 패턴을 조사했어."],
  question: ["inquiry", "질문, 탐구", "라틴어 inquirere는 안으로 찾아 들어가다라는 뜻이에요. 답을 얻기 위해 자세히 묻는 일이죠.", "Her inquiry led to a new discovery.", "그녀의 탐구는 새로운 발견으로 이어졌어."],
  answer: ["response", "응답, 반응", "라틴어 respondere는 다시 약속하거나 답하다라는 뜻이에요. 질문이나 상황에 되돌려 주는 반응이죠.", "His response was thoughtful and precise.", "그의 답변은 사려 깊고 정확했어."],
  idea: ["notion", "생각, 개념", "라틴어 notio는 알게 됨이나 개념을 뜻해요. 마음속에 형성된 생각을 가리켜요.", "She challenged the common notion of success.", "그녀는 성공에 대한 흔한 통념에 의문을 제기했어."],
  create: ["generate", "생성하다, 만들어 내다", "라틴어 generare는 낳다, 생기게 하다라는 뜻이에요. 새로운 결과가 태어나게 하는 말이죠.", "The workshop generated several bold ideas.", "그 워크숍은 여러 대담한 아이디어를 만들어 냈어."],
  imagine: ["envision", "마음속에 그리다", "en과 vision이 합쳐져 어떤 미래나 모습을 눈앞에 보듯 상상한다는 뜻이에요.", "Envision the person you want to become.", "되고 싶은 자신의 모습을 마음속에 그려 봐."],
  design: ["devise", "고안하다", "라틴어 dividere에서 프랑스어를 거치며 계획을 나누고 정리해 만들어 낸다는 뜻이 됐어요.", "They devised a clever solution.", "그들은 영리한 해결책을 고안했어."],
  pattern: ["configuration", "배열, 구성", "라틴어 configurare는 함께 형태를 만들다라는 뜻이에요. 여러 요소가 놓인 전체 모습을 말해요.", "The new configuration created more space.", "새로운 배치가 더 많은 공간을 만들었어."],
  method: ["approach", "접근법, 방식", "옛 프랑스어 aprochier는 가까이 가다라는 뜻이에요. 문제 가까이 다가가는 방식이 approach가 됐죠.", "We tried a different approach to the problem.", "우리는 그 문제에 다른 방식으로 접근했어."],
  habit: ["tendency", "경향, 성향", "라틴어 tendere는 어떤 방향으로 뻗다라는 뜻이에요. 자주 향하게 되는 행동이나 생각을 말해요.", "She has a tendency to notice small details.", "그녀는 작은 세부를 알아차리는 경향이 있어."],
  routine: ["regimen", "규칙적인 과정, 관리법", "라틴어 regere는 다스리고 이끌다라는 뜻이에요. 정해진 방식으로 생활을 관리하는 과정이죠.", "A simple regimen helped him stay focused.", "간단한 생활 관리법이 그의 집중을 도왔어."],
  patience: ["perseverance", "인내와 끈기", "라틴어 perseverare는 엄격하게 계속하다라는 뜻이에요. 어려움 속에서도 멈추지 않는 힘이죠.", "Perseverance carried her through the challenge.", "끈기가 그녀를 도전의 끝까지 이끌었어."],
  challenge: ["obstacle", "장애물, 난관", "라틴어 obstare는 앞을 가로막고 서다라는 뜻이에요.", "Every obstacle taught us something useful.", "모든 난관은 우리에게 유용한 것을 가르쳐 줬어."],
  achieve: ["accomplish", "성취하다, 완수하다", "라틴어 complere는 완전히 채우다라는 뜻이에요. 해야 할 일을 끝까지 채워 마치는 거예요.", "We accomplished more than we expected.", "우리는 예상보다 더 많은 일을 해냈어."],
  success: ["attainment", "성취, 달성", "attain은 라틴어 attingere, 곧 손을 뻗어 닿다에서 왔어요. 목표에 닿은 결과가 attainment예요.", "The award marked a significant attainment.", "그 상은 중요한 성취를 나타냈어."],
  wisdom: ["discernment", "분별력, 통찰", "라틴어 discernere는 서로 다른 것을 가려 나누다라는 뜻이에요. 중요한 차이를 알아보는 지혜죠.", "Good leadership requires discernment.", "좋은 리더십에는 분별력이 필요해."],
  knowledge: ["expertise", "전문 지식, 전문성", "라틴어 expertus는 직접 시험해 본이라는 뜻이에요. 경험으로 쌓은 깊은 지식을 말해요.", "Her expertise solved the difficult problem.", "그녀의 전문 지식이 어려운 문제를 해결했어."],
  mystery: ["enigma", "수수께끼 같은 존재", "그리스어 ainigma는 돌려 말한 수수께끼를 뜻해요. 쉽게 풀리지 않는 사람이나 사건에도 쓰여요.", "The silent tower remained an enigma.", "그 고요한 탑은 여전히 수수께끼로 남았어."],
  magic: ["enchantment", "마법, 황홀하게 함", "옛 프랑스어 enchanter는 노래나 주문으로 매혹하다라는 뜻이에요.", "The lanterns gave the garden an air of enchantment.", "등불은 정원에 마법 같은 분위기를 더했어."],
  phantom: ["apparition", "유령 같은 형상", "라틴어 apparere는 나타나다라는 뜻이에요. 갑자기 눈앞에 나타난 신비한 형상을 가리켜요.", "An apparition appeared beside the window.", "창가에 유령 같은 형상이 나타났어."],
  monster: ["creature", "생물, 창조된 존재", "라틴어 creatura는 만들어진 것을 뜻해요. 실제 생물부터 상상의 존재까지 폭넓게 가리켜요.", "The gentle creature offered us tea.", "그 온순한 생물은 우리에게 차를 건넸어."],
  shadow: ["penumbra", "반그림자, 희미한 경계", "라틴어 paene는 거의, umbra는 그림자를 뜻해요. 빛과 어둠 사이의 흐릿한 부분을 가리켜요.", "The fox waited in the moon’s penumbra.", "여우는 달빛의 희미한 반그림자 속에서 기다렸어."],
  costume: ["disguise", "변장, 위장", "옛 프랑스어 desguiser는 본래 모습과 다르게 꾸미다라는 뜻이에요.", "Her clever disguise fooled everyone.", "그녀의 영리한 변장은 모두를 속였어."],
  mask: ["facade", "겉모습, 표면적 인상", "프랑스어 façade는 건물의 앞면을 뜻해요. 감정이나 진실을 가리는 겉모습이라는 뜻도 생겼죠.", "His calm facade hid his excitement.", "그의 차분한 겉모습은 설렘을 감추고 있었어."],
  spell: ["incantation", "주문, 마법의 문구", "라틴어 incantare는 안으로 노래하다라는 뜻이에요. 특별한 힘을 바라는 말이나 노래를 가리켜요.", "The wizard recited an ancient incantation.", "마법사는 오래된 주문을 읊었어."],
  charm: ["allure", "강한 매력", "프랑스어 aleurer는 미끼로 끌어당기다라는 뜻에서 매혹하는 힘이라는 뜻으로 발전했어요.", "The hidden garden had a quiet allure.", "숨겨진 정원에는 잔잔한 매력이 있었어."],
  potion: ["elixir", "영약, 묘약", "아랍어 al-iksir는 물질을 변화시킨다고 믿은 연금술의 약을 뜻했어요.", "The healer prepared a fragrant elixir.", "치유사는 향기로운 영약을 준비했어."],
  secret: ["confidential", "기밀의, 비밀로 다루는", "라틴어 confidere는 함께 믿다라는 뜻이에요. 믿는 사이에서만 나누는 정보라는 느낌이죠.", "The document contains confidential details.", "그 문서에는 기밀 정보가 담겨 있어."],
  puzzle: ["conundrum", "난제, 수수께끼", "conundrum은 16세기 영어에서 장난스러운 수수께끼를 가리켰지만 정확한 기원은 알려지지 않았어요.", "The final question was a real conundrum.", "마지막 문제는 정말 어려운 난제였어."],
  maze: ["labyrinth", "복잡한 미로", "그리스 신화에서 미노타우로스를 가둔 복잡한 건축물 Labyrinthos에서 온 말이에요.", "A silver thread guided us through the labyrinth.", "은빛 실이 우리를 미로 밖으로 안내했어."],
  riddle: ["brainteaser", "머리를 쓰는 수수께끼", "brain과 teaser가 합쳐져 머리를 골똘히 쓰게 만드는 문제를 뜻해요.", "The brainteaser looked simple but was difficult.", "그 수수께끼는 간단해 보였지만 어려웠어."],
  story: ["narrative", "서사, 이야기", "라틴어 narrare는 말해 알리다라는 뜻이에요. 사건을 이어 들려주는 방식이나 이야기를 가리켜요.", "The novel unfolds through two narratives.", "그 소설은 두 개의 서사를 통해 펼쳐져."],
  wonder: ["awe", "경외감, 벅찬 놀라움", "고대 노르스어 agi는 두려움과 존경이 섞인 강한 감정을 뜻했어요.", "We gazed at the glacier in awe.", "우리는 경외감에 차 빙하를 바라봤어."],
  strange: ["peculiar", "특이한, 독특한", "라틴어 peculiaris는 개인에게 속한이라는 뜻이에요. 남들과 다른 고유한 특징을 가리키게 됐죠.", "A peculiar light glowed beneath the door.", "문 아래에서 특이한 빛이 새어 나왔어."],
  eerie: ["uncanny", "기묘하고 섬뜩한", "un과 canny가 합쳐져 익숙하게 이해할 수 없는 기묘한 느낌을 나타내요.", "The empty station felt strangely uncanny.", "빈 역은 이상하리만큼 기묘하게 느껴졌어."],
  community: ["collective", "공동체, 집단", "라틴어 colligere는 함께 모으다라는 뜻이에요. 공동의 목적을 가진 집단을 가리켜요.", "The artists formed a creative collective.", "예술가들은 창작 공동체를 만들었어."],
  neighbor: ["resident", "거주자, 주민", "라틴어 residere는 한곳에 머물러 앉다라는 뜻이에요.", "Every resident joined the garden project.", "모든 주민이 정원 프로젝트에 참여했어."],
  family: ["kinship", "친족 관계, 유대", "고대 영어 cynn은 가족과 혈족을 뜻해요. 사람 사이의 가까운 유대를 가리키기도 해요.", "Shared memories strengthened their kinship.", "함께한 기억이 그들의 유대를 단단하게 했어."],
  friend: ["confidant", "마음을 털어놓는 친구", "프랑스어 confident는 믿고 비밀을 나누는 사람을 뜻해요.", "She trusted her closest confidant.", "그녀는 가장 가까운 친구를 믿었어."],
  culture: ["heritage", "문화유산, 전통", "옛 프랑스어 heriter는 물려받다라는 뜻이에요. 세대에서 세대로 이어받은 문화와 가치를 말해요.", "The festival celebrates the region’s heritage.", "그 축제는 지역의 문화유산을 기념해."],
  custom: ["convention", "관습, 관례", "라틴어 convenire는 함께 모이다라는 뜻이에요. 사람들이 함께 받아들인 방식이 관례가 됐죠.", "By convention, guests speak first.", "관례상 손님이 먼저 말해."],
  tradition: ["legacy", "유산, 전해진 가치", "라틴어 legare는 맡기거나 물려주다라는 뜻이에요. 다음 세대에 남겨진 것이 legacy예요.", "Her kindness became a lasting legacy.", "그녀의 친절은 오래 남는 유산이 됐어."],
  dialogue: ["discourse", "담화, 진지한 대화", "라틴어 discurrere는 이리저리 달리다라는 뜻이에요. 생각이 오가며 펼쳐지는 대화를 가리켜요.", "The lecture inspired public discourse.", "그 강연은 사회적 논의를 불러일으켰어."],
  promise: ["commitment", "약속, 헌신", "라틴어 committere는 함께 맡기다라는 뜻이에요. 자신을 어떤 선택이나 책임에 묶는 말이죠.", "The project requires long-term commitment.", "그 프로젝트에는 장기적인 헌신이 필요해."],
  trust: ["reliance", "신뢰, 의지", "rely와 이어진 말로 누군가나 무언가에 기대는 상태를 뜻해요.", "Mutual reliance strengthened the team.", "서로에 대한 신뢰가 팀을 단단하게 했어."],
  respect: ["esteem", "존경, 높은 평가", "라틴어 aestimare는 가치를 판단하다라는 뜻이에요. 누군가의 가치를 높게 여기는 마음이죠.", "Her integrity earned everyone’s esteem.", "그녀의 성실함은 모두의 존경을 얻었어."],
  justice: ["equity", "공정함, 형평성", "라틴어 aequus는 평평하고 공평한이라는 뜻이에요. 상황에 맞게 공정한 기회를 주는 개념이죠.", "The policy aims to improve equity.", "그 정책은 형평성을 높이는 것을 목표로 해."],
  peace: ["tranquility", "평온, 고요", "라틴어 tranquillus는 잔잔하고 동요가 없다는 뜻이에요.", "The garden offered a sense of tranquility.", "그 정원은 평온함을 느끼게 했어."],
  leader: ["pioneer", "개척자, 선구자", "옛 프랑스어 peonier는 보병을 뜻했어요. 앞에서 길을 닦는 사람이라는 뜻으로 발전했죠.", "She became a pioneer in digital art.", "그녀는 디지털 예술의 선구자가 되었어."],
  team: ["alliance", "동맹, 협력 관계", "라틴어 alligare는 서로 묶다라는 뜻이에요. 공동 목표를 위해 연결된 관계를 말해요.", "The groups formed an alliance.", "그 단체들은 동맹을 맺었어."],
  cooperate: ["collaborate", "협업하다", "라틴어 collaborare는 함께 일하다라는 뜻이에요. co는 함께, labor는 일이에요.", "Designers and engineers collaborated closely.", "디자이너와 개발자는 긴밀하게 협업했어."],
  support: ["reinforce", "강화하다, 뒷받침하다", "re와 프랑스어 enforce가 만나 힘을 더한다는 뜻이 됐어요.", "The evidence reinforced her argument.", "그 증거는 그녀의 주장을 뒷받침했어."],
  volunteer: ["contribute", "기여하다", "라틴어 contribuere는 함께 가져오다라는 뜻이에요. 공동의 결과에 자신의 몫을 보태는 일이죠.", "Everyone contributed to the final result.", "모두가 최종 결과에 기여했어."],
  charity: ["philanthropy", "박애, 자선 활동", "그리스어 philos는 사랑, anthropos는 인간을 뜻해요. 사람을 사랑해 돕는 활동이죠.", "The foundation supports education through philanthropy.", "그 재단은 자선 활동으로 교육을 지원해."],
  kindness: ["compassion", "연민, 따뜻한 배려", "라틴어 compati는 함께 아파하다라는 뜻이에요. 타인의 어려움을 느끼고 돕는 마음이죠.", "Compassion moved her to help the stranger.", "연민은 그녀가 낯선 이를 돕게 했어."],
  generous: ["benevolent", "자비로운, 선의의", "라틴어 bene는 잘, velle는 바라다라는 뜻이에요. 다른 이의 행복을 바라는 태도를 말해요.", "A benevolent donor funded the library.", "한 자비로운 후원자가 도서관을 지원했어."],
  harmony: ["cohesion", "결속, 조화", "라틴어 cohaerere는 함께 달라붙다라는 뜻이에요. 여러 부분이 단단히 어우러진 상태죠.", "Clear goals improved the team’s cohesion.", "분명한 목표가 팀의 결속을 높였어."],
  unity: ["solidarity", "연대, 결속", "라틴어 solidus는 단단한 하나를 뜻해요. 서로를 지지하며 하나가 된 마음이죠.", "The community showed solidarity after the storm.", "마을 사람들은 폭풍 뒤에 연대를 보여 줬어."],
  holiday: ["respite", "잠깐의 휴식", "라틴어 respectus는 뒤돌아봄과 쉼의 뜻을 거쳐, 힘든 일 사이의 짧은 휴식을 가리키게 됐어요.", "The quiet weekend offered a welcome respite.", "조용한 주말은 반가운 휴식이 되었어."],
  celebrate: ["commemorate", "기념하다", "라틴어 commemorare는 함께 기억하다라는 뜻이에요. 중요한 사람이나 사건을 기억하며 기리는 일이죠.", "The ceremony commemorates a historic achievement.", "그 행사는 역사적인 성취를 기념해."],
  gift: ["token", "표시, 작은 선물", "고대 영어 tacen은 표시나 증거를 뜻했어요. 마음을 보여 주는 작은 물건도 token이라 불러요.", "She gave him a token of appreciation.", "그녀는 감사의 표시로 작은 선물을 주었어."],
  surprise: ["astonishment", "큰 놀라움", "라틴어 extonare는 천둥을 맞은 듯 놀라게 하다라는 뜻이에요.", "The discovery filled us with astonishment.", "그 발견은 우리를 크게 놀라게 했어."],
  merry: ["jubilant", "매우 기뻐하는", "라틴어 jubilare는 기뻐 외치다라는 뜻이에요. 기쁨이 밖으로 터져 나오는 상태를 말해요.", "The crowd was jubilant after the victory.", "승리 뒤 군중은 크게 기뻐했어."],
  joy: ["elation", "큰 기쁨, 환희", "라틴어 efferre는 위로 들어 올리다라는 뜻이에요. 마음이 높이 들린 듯한 기쁨을 표현해요.", "She felt a surge of elation.", "그녀는 벅찬 기쁨이 밀려오는 것을 느꼈어."],
  hope: ["optimism", "낙관, 희망적인 태도", "라틴어 optimus는 가장 좋은이라는 뜻이에요. 좋은 결과를 기대하는 태도가 optimism이죠.", "His optimism encouraged the whole team.", "그의 낙관적인 태도는 팀 전체를 북돋았어."],
  wish: ["aspiration", "열망, 포부", "라틴어 aspirare는 숨을 불어넣거나 향해 나아가다라는 뜻이에요. 이루고 싶은 높은 바람을 말해요.", "Her aspiration is to become an architect.", "그녀의 포부는 건축가가 되는 거야."],
  dream: ["reverie", "몽상, 즐거운 공상", "프랑스어 rêver는 꿈꾸다라는 뜻이에요. 깨어 있는 동안 빠지는 부드러운 공상을 가리켜요.", "He drifted into a peaceful reverie.", "그는 평화로운 몽상에 잠겼어."],
  comfort: ["solace", "위안, 위로", "라틴어 solari는 달래고 위로하다라는 뜻이에요. 슬픔이나 어려움을 누그러뜨리는 것을 말해요.", "She found solace in music.", "그녀는 음악에서 위안을 찾았어."],
  home: ["sanctuary", "안식처, 피난처", "라틴어 sanctuarium은 신성하고 안전한 장소를 뜻했어요. 마음 편히 쉴 수 있는 곳에도 써요.", "The small cabin became our sanctuary.", "그 작은 오두막은 우리의 안식처가 되었어."],
  fireplace: ["hearth", "벽난로 바닥, 따뜻한 가정", "고대 영어 heorth는 불을 피우는 집의 중심을 뜻했어요. 따뜻한 가정 자체를 상징하기도 해요.", "The family gathered around the hearth.", "가족은 따뜻한 난롯가에 모였어."],
  sparkle: ["shimmer", "은은하게 반짝이다", "고대 영어 scimerian은 희미하게 빛나다라는 뜻이에요. 빛이 부드럽게 흔들리는 모습을 말해요.", "The snow shimmered beneath the moon.", "눈이 달빛 아래 은은하게 반짝였어."],
  music: ["melody", "선율", "그리스어 melodia는 노래와 가락을 뜻해요. melos는 노래, ode는 노래하는 시예요.", "A gentle melody drifted through the street.", "부드러운 선율이 거리를 흘러갔어."],
  souvenir: ["memento", "기념품, 추억의 물건", "라틴어 memento는 기억하라는 뜻이에요. 어떤 순간을 떠올리게 하는 물건을 가리켜요.", "The shell became a memento of our trip.", "그 조개껍데기는 여행의 기념품이 되었어."],
  reflect: ["contemplate", "깊이 생각하다", "라틴어 contemplari는 정해진 공간을 자세히 바라보다라는 뜻이에요. 한 생각을 오래 들여다보는 일이죠.", "She contemplated the choices ahead.", "그녀는 앞으로의 선택을 깊이 생각했어."],
  forgive: ["reconcile", "화해하다, 조정하다", "라틴어 reconciliare는 다시 함께 불러 모으다라는 뜻이에요. 멀어진 관계를 다시 잇는 말이죠.", "The two friends decided to reconcile.", "두 친구는 화해하기로 했어."],
  reunion: ["homecoming", "귀향, 오랜만의 귀환", "home과 coming이 합쳐져 집이나 익숙한 공동체로 돌아오는 일을 뜻해요.", "The village prepared a joyful homecoming.", "마을은 기쁜 귀환을 준비했어."],
  farewell: ["departure", "출발, 떠남", "라틴어 departire는 나누어 떨어지다라는 뜻이에요. 한 장소나 사람을 떠나는 일을 가리켜요.", "Their departure marked the end of an era.", "그들의 떠남은 한 시대의 끝을 알렸어."],
  future: ["prospect", "전망, 가능성", "라틴어 prospicere는 앞을 내다보다라는 뜻이에요. 앞으로 펼쳐질 가능성을 가리켜요.", "The prospect of change excited everyone.", "변화의 가능성은 모두를 설레게 했어."],
  new: ["novel", "새로운, 참신한", "라틴어 novus는 새롭다는 뜻이에요. 이전에 없던 참신한 생각이나 방식에 써요.", "They proposed a novel solution.", "그들은 참신한 해결책을 제안했어."],
  resolution: ["resolve", "굳은 결심", "라틴어 resolvere는 다시 풀어내다라는 뜻이에요. 문제를 정리하고 마음을 확고히 한다는 뜻이 생겼죠.", "Her resolve remained strong.", "그녀의 결심은 굳건했어."],
  cheer: ["encourage", "격려하다", "프랑스어 encoragier는 마음에 용기를 넣다라는 뜻이에요. courage와 같은 심장의 뿌리를 가져요.", "A few kind words encouraged him.", "몇 마디 다정한 말이 그를 격려했어."],
};

export function applyVocabularyUpgrades(words: DailyWord[]): DailyWord[] {
  return words.map((item) => {
    const upgrade = UPGRADES[item.word];
    if (!upgrade) return item;
    const [word, meaning, origin, example, translation] = upgrade;
    return {
      ...item,
      word,
      pronunciation: "눌러서 발음 듣기",
      meaning,
      description: `${meaning}을 자연스럽게 익혀 두면 표현의 폭이 넓어져요`,
      originTitle: `${word}의 뿌리에는 어떤 장면이 숨어 있을까요?`,
      origin,
      example,
      translation,
    };
  });
}
